"use client";

import { CSSProperties, useMemo, useState } from "react";
import { analyzeProject } from "../lib/health";
import { catalogRegistry } from "../lib/catalog-registry";
import { DesignSystemProject, PlatformId, platformOrder } from "../lib/model";
import { resolveProjectTokens } from "../lib/token-resolver";
import { ProjectAlertPreview } from "./ProjectPreviews";
import { Alert, Badge, Button, Card, SectionHeading, Select, Table } from "./ui/LabUI";
import { ChevronDownIcon } from "./ui/Icons";

type Props = { project: DesignSystemProject; onOpenTokens: (token: string) => void; onOpenCatalog: (component?: string) => void };

function Scenario({ project, platform, theme }: { project: DesignSystemProject; platform: PlatformId; theme: string }) {
  const snapshot = resolveProjectTokens(project, theme, platform);
  return <article className={`health-scenario scenario-${platform}`}><header><div><span>{project.meta.brandMark}</span><b>{project.meta.name}</b></div><nav>Inicio&nbsp;&nbsp; Equipo&nbsp;&nbsp; Ajustes</nav></header><main><div className="scenario-title"><div><small>Equipo de producto</small><h3>Revisión del sistema</h3><p>Comprobá el formulario y la tabla antes de publicar.</p></div><button>Crear revisión</button></div><div className="scenario-grid"><section><h4>Nueva revisión</h4><label>Nombre<input defaultValue="Auditoría de contraste" /></label><label>Responsable<button className="scenario-select" role="combobox" aria-expanded="false" aria-controls={`${platform}-responsible-options`}>Equipo de diseño <ChevronDownIcon /></button><span hidden role="listbox" id={`${platform}-responsible-options`}><span role="option" aria-selected="true">Equipo de diseño</span></span></label><div className="scenario-feedback"><ProjectAlertPreview state="Warning">Hay decisiones heredadas que requieren revisión.</ProjectAlertPreview></div><button>Guardar cambios</button></section><section><h4>Actividad reciente</h4><div className="scenario-table"><div><b>Foundation</b><b>Estado</b></div><div><span>Paleta primaria</span><em>Lista</em></div><div><span>Grilla responsiva</span><em>Pendiente</em></div><div><span>Tokens de foco</span><em>Lista</em></div></div></section></div></main>{!snapshot.ready ? <div className="scenario-pending">Configuración pendiente: {snapshot.missing.length} referencias</div> : null}</article>;
}

export function HealthView({ project, onOpenTokens, onOpenCatalog }: Props) {
  const health = analyzeProject(project);
  const enabledPlatforms = platformOrder.filter((id) => project.platforms[id].enabled);
  const [theme, setTheme] = useState(project.themes[0]?.id || "light");
  const coverage = useMemo(() => project.themes.flatMap((mode) => enabledPlatforms.map((platform) => {
    const snapshot = resolveProjectTokens(project, mode.id, platform);
    const missingComponents = catalogRegistry.filter((entry) => entry.componentTokens.some((name) => !project.componentTokens.some((token) => token.name === name)));
    const errors = snapshot.ready ? 0 : Math.max(1, snapshot.missing.length);
    const warnings = project.platforms[platform].proposalPending ? 1 : missingComponents.length;
    const covered = catalogRegistry.length - missingComponents.length;
    return { mode, platform, snapshot, total: catalogRegistry.length, errors, warnings, uncovered: missingComponents.length, covered };
  })), [project, enabledPlatforms]);

  if (health.status === "not-evaluated") return <div className="health-v4"><SectionHeading title="Salud del sistema" description="La evaluación empieza cuando existe una base mínima. Un proyecto en blanco no está fallando: todavía está pendiente de configuración." /><Alert tone="info" title="Sin evaluar" action={<Button onClick={() => onOpenTokens("surface.default")}>Configurar primeros tokens</Button>}>Creá una paleta, asigná roles semánticos esenciales y conectá decisiones de componente para iniciar la cobertura.</Alert><Card><SectionHeading level={2} title="Ruta recomendada" description="1. Foundations de color y tipografía · 2. Tokens semánticos · 3. Catálogo · 4. Salud global" /></Card></div>;

  return <div className="health-v4">
    <SectionHeading title="Salud del sistema" description="Vista consolidada para priorizar coherencia global por modo, plataforma y componente. Las métricas llevan al punto exacto de inspección." action={<Select label="Modo del escenario" value={theme} onValueChange={setTheme} options={project.themes.map((mode) => ({ value: mode.id, label: mode.name }))} />} />
    <section className="health-summary-v4"><Card className="health-score-v4"><div className="score-ring" style={{ "--score": `${(health.score || 0) * 3.6}deg` } as CSSProperties}><span>{health.score}</span></div><div><Badge tone={health.counts.blocking ? "danger" : "success"}>{health.counts.blocking ? "Requiere atención" : "Listo para explorar"}</Badge><h2>{health.summary}</h2><p>El resultado se explica con los hallazgos y la cobertura visibles debajo.</p></div></Card><Card><SectionHeading level={2} title="Hallazgos activos" /><div className="health-stat-row"><button onClick={() => onOpenTokens(health.findings.find((finding) => finding.severity === "blocking")?.area || "")}><b>{health.counts.blocking}</b><span>Errores</span></button><button onClick={() => onOpenCatalog()}><b>{health.counts.warning}</b><span>Advertencias</span></button><button onClick={() => onOpenCatalog()}><b>{health.counts.recommendation}</b><span>Recomendaciones</span></button></div></Card></section>
    <Card><SectionHeading level={2} title="Cobertura por modo y plataforma" description={`${catalogRegistry.length} componentes del registro se evalúan en cada combinación activa.`} /><Table><thead><tr><th>Modo</th><th>Plataforma</th><th>Evaluados</th><th>Con error</th><th>Con advertencia</th><th>Sin cobertura</th><th>Acción</th></tr></thead><tbody>{coverage.map((row) => <tr key={`${row.mode.id}-${row.platform}`}><td>{row.mode.name}</td><td>{project.platforms[row.platform].name}</td><td><b>{row.total}</b></td><td><button className={`metric-link ${row.errors ? "error" : ""}`} onClick={() => onOpenTokens(row.snapshot.missing[0] || "")}>{row.errors}</button></td><td><button className={`metric-link ${row.warnings ? "warning" : ""}`} onClick={() => onOpenCatalog()}>{row.warnings}</button></td><td><button className="metric-link" onClick={() => onOpenCatalog()}>{row.uncovered}</button></td><td><Button size="sm" variant="quiet" onClick={() => row.errors ? onOpenTokens(row.snapshot.missing[0] || "") : onOpenCatalog()}>Inspeccionar</Button></td></tr>)}</tbody></Table></Card>
    <Card><SectionHeading level={2} title="Hallazgos priorizados" description="Cada hallazgo incluye contexto, causa y acción correctiva." />{health.findings.length ? <div className="health-findings-v4">{health.findings.map((finding) => <article key={finding.id}><Badge tone={finding.severity === "blocking" ? "danger" : finding.severity === "warning" ? "warning" : "info"}>{finding.severity === "blocking" ? "Error" : finding.severity === "warning" ? "Advertencia" : "Recomendación"}</Badge><div><small>{finding.mode} · {finding.platform} · {finding.area}</small><h3>{finding.cause}</h3><p>{finding.action}</p></div><Button size="sm" onClick={() => finding.section === "catalog" ? onOpenCatalog() : onOpenTokens(finding.area)}>Corregir</Button></article>)}</div> : <Alert tone="success" title="Sin bloqueantes">El sistema inicial resuelve los roles, referencias y contrastes esenciales.</Alert>}</Card>
    <section><SectionHeading level={2} title="Escenarios comparativos" description="El mismo flujo de producto en Mobile, Tablet y Desktop. Las plataformas inactivas muestran la propuesta heredada para anticipar decisiones." /><div className="health-scenarios">{(["mobile", "tablet", "desktop"] as PlatformId[]).map((platform) => { const snapshot = resolveProjectTokens(project, theme, platform); return <div key={platform}><div className="scenario-label"><b>{project.platforms[platform].name}</b><span>{!project.platforms[platform].enabled ? "Propuesta heredada · inactiva" : snapshot.ready ? "Tokens resueltos" : "Configuración pendiente"}</span></div><div style={snapshot.cssVariables as CSSProperties}><Scenario project={project} platform={platform} theme={theme} /></div></div>; })}</div></section>
  </div>;
}
