import type { Meta, StoryObj } from "@storybook/react-vite";
import { useState } from "react";
import { Alert, Badge, Button, Card, Checkbox, Combobox, ExportMenu, HealthIndicator, Input, ProjectMenu, RadioGroup, SectionHeading, Select, Switch, Table, Tabs, Textarea } from "./LabUI";

const meta = { title: "Laboratorio/Biblioteca interna", parameters: { layout: "padded" } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

export const AccionesYEstados: Story = { render: () => <div className="story-grid"><Button variant="primary">Primario</Button><Button variant="secondary">Secundario</Button><Button variant="danger">Destructivo</Button><Button disabled>Deshabilitado</Button><Button className="is-hover">Hover</Button><Button className="is-focus">Focus</Button><Button className="is-active">Active</Button></div> };
export const Campos: Story = { render: () => <div className="story-stack"><Input label="Nombre del proyecto" defaultValue="Atlas Design System" help="Se usa en documentación y exportaciones." /><Input label="Email" defaultValue="equipo@" error="Ingresá un email válido." /><Input label="Ancho máximo" defaultValue="1280" suffix="px" /><Textarea label="Descripción" defaultValue="Contenido largo para validar que el campo conserve ritmo, altura y legibilidad incluso en documentación extensa." /></div> };
export const SelectYCombobox: Story = { render: () => { const Demo = () => { const [select, setSelect] = useState("mobile"); const [font, setFont] = useState("inter"); return <div className="story-stack"><Select label="Plataforma" value={select} onValueChange={setSelect} options={[{ value: "mobile", label: "Mobile" }, { value: "tablet", label: "Tablet" }, { value: "desktop", label: "Desktop" }]} /><Combobox label="Familia tipográfica" value={font} onValueChange={setFont} options={[{ value: "inter", label: "Inter", meta: "Google Fonts" }, { value: "arial", label: "Arial", meta: "Común" }, { value: "custom", label: "Marca Sans", meta: "Personalizada" }]} /></div>; }; return <Demo />; } };
export const Seleccion: Story = { render: () => { const Demo = () => { const [check, setCheck] = useState(true); const [sw, setSw] = useState(false); const [radio, setRadio] = useState("a"); return <div className="story-stack"><Checkbox checked={check} onCheckedChange={setCheck} label="Exportar foundations" /><Checkbox checked={false} onCheckedChange={() => {}} label="Opción deshabilitada" disabled /><Switch checked={sw} onCheckedChange={setSw} label="Activar tablet" /><RadioGroup value={radio} onValueChange={setRadio} options={[{ value: "a", label: "Escala suave" }, { value: "b", label: "Cuarta perfecta" }]} /></div>; }; return <Demo />; } };
export const Menus: Story = { render: () => <div className="story-grid"><ProjectMenu onImport={() => {}} onDownload={() => {}} onDuplicate={() => {}} /><ExportMenu onConfigure={() => {}} onQuickExport={() => {}} /></div> };
export const EncabezadosYSalud: Story = { render: () => <div className="story-stack"><SectionHeading title="Foundations" description="Decisiones primitivas sin intención de uso." /><SectionHeading level={2} title="Tipografía" description="Familia, estilo base y escala modular con contenido deliberadamente largo para probar saltos de línea." /><div className="story-grid"><HealthIndicator score={100} status="ready" summary="Sistema listo" onClick={() => {}} /><HealthIndicator score={72} status="attention" summary="Requiere atención" onClick={() => {}} /><HealthIndicator score={null} status="pending" summary="Sin evaluar" onClick={() => {}} /></div></div> };
export const SuperficiesYFeedback: Story = { render: () => <div className="story-stack"><div className="story-grid"><Badge>Neutral</Badge><Badge tone="success">Validado</Badge><Badge tone="warning">Pendiente</Badge><Badge tone="danger">Error</Badge></div><Alert tone="warning" title="Revisión requerida">La grilla de tablet todavía hereda los valores móviles.</Alert><Card><SectionHeading level={2} title="Card de ejemplo" description="Superficie interna reutilizable." /></Card><Table><thead><tr><th>Rol</th><th>Foundation</th><th>Estado</th></tr></thead><tbody><tr><td>Texto principal</td><td>Slate.900</td><td><Badge tone="success">Asignado</Badge></td></tr></tbody></Table></div> };
export const TabsInteractivos: Story = { render: () => { const Demo = () => { const [value, setValue] = useState("uno"); return <Tabs value={value} onValueChange={setValue} ariaLabel="Secciones" tabs={[{ value: "uno", label: "Resumen", content: <p>Contenido del resumen.</p> }, { value: "dos", label: "Tokens", content: <p>Contenido de tokens.</p> }]} />; }; return <Demo />; } };
export const ClaroOscuroYContenidoLargo: Story = { render: () => <div className="story-stack" style={{ maxWidth: 980 }}><div className="storybook-frame theme-light" data-lab-theme="light"><SectionHeading title="Tema claro" description="Ejemplo extenso para comprobar saltos de línea, jerarquía estable y controles que no colapsan cuando las etiquetas ocupan más espacio del habitual." /><div className="story-grid"><ProjectMenu onImport={() => {}} onDownload={() => {}} onDuplicate={() => {}} /><ExportMenu onConfigure={() => {}} onQuickExport={() => {}} /><HealthIndicator score={88} status="attention" summary="Dos decisiones requieren revisión" onClick={() => {}} /></div></div><div className="storybook-frame theme-dark" data-lab-theme="dark"><SectionHeading title="Tema oscuro" description="La misma composición conserva contraste, espaciado y estados sin modificar los tokens del proyecto que se esté evaluando." /><div className="story-grid"><Button variant="primary">Acción con una etiqueta deliberadamente larga</Button><Checkbox checked onCheckedChange={() => {}} label="Incluir todos los modos y plataformas activos en esta exportación" /><Switch checked onCheckedChange={() => {}} label="Activar propuesta heredada" /></div></div></div> };
